<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\gLAMS.Application\gLAMS.Application.csproj" />
    <ProjectReference Include="..\gLAMS.Infrastructure\gLAMS.Infrastructure.csproj" />
    <ProjectReference Include="..\gLAMS.Shared\gLAMS.Shared.csproj" />
  </ItemGroup>

</Project>
